USER admin meit {
SELECT cast((cast(meit as float) - 1) * 1 as int) as key0,SUM(nox*1) AS nox FROM DB_2017 WHERE (meit >= 1 AND meit <= 23) AND nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT prov as key0,SUM(nox*1) AS nox FROM DB_2015 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT class as key0,SUM(nox*1) AS nox FROM DB_2015 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT type as key0,SUM(nox*1) AS nox FROM DB_2015 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT mode as key0,SUM(nox*1) AS nox FROM DB_2015 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT engine as key0,SUM(nox*1) AS nox FROM DB_2015 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT ocountry as key0,SUM(nox*1) AS nox FROM DB_2015 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT dcountry as key0,SUM(nox*1) AS nox FROM DB_2015 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT otrip as key0,SUM(nox*1) AS nox FROM DB_2015 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT dtrip as key0,SUM(nox*1) AS nox FROM DB_2015 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT extract(dow from datet) as key0,SUM(nox*1) AS nox FROM DB_2015 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT extract(hour from datet) as key0,SUM(nox*1) AS nox FROM DB_2015 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT ip as key0,SUM(nox*1) AS nox FROM DB_2015 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;

SELECT cast((cast(meit as float) - 1) * 1 as int) as key0,SUM(nox*1) AS nox FROM DB_2016 WHERE (meit >= 1 AND meit <= 23) AND nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT prov as key0,SUM(nox*1) AS nox FROM DB_2016 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT class as key0,SUM(nox*1) AS nox FROM DB_2016 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT type as key0,SUM(nox*1) AS nox FROM DB_2016 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT mode as key0,SUM(nox*1) AS nox FROM DB_2016 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT engine as key0,SUM(nox*1) AS nox FROM DB_2016 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT ocountry as key0,SUM(nox*1) AS nox FROM DB_2016 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT dcountry as key0,SUM(nox*1) AS nox FROM DB_2016 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT otrip as key0,SUM(nox*1) AS nox FROM DB_2016 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT dtrip as key0,SUM(nox*1) AS nox FROM DB_2016 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT extract(dow from datet) as key0,SUM(nox*1) AS nox FROM DB_2016 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT extract(hour from datet) as key0,SUM(nox*1) AS nox FROM DB_2016 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT ip as key0,SUM(nox*1) AS nox FROM DB_2016 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;

SELECT cast((cast(meit as float) - 1) * 1 as int) as key0,SUM(nox*1) AS nox FROM DB_2017 WHERE (meit >= 1 AND meit <= 23) AND nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT prov as key0,SUM(nox*1) AS nox FROM DB_2017 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT class as key0,SUM(nox*1) AS nox FROM DB_2017 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT type as key0,SUM(nox*1) AS nox FROM DB_2017 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT mode as key0,SUM(nox*1) AS nox FROM DB_2017 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT engine as key0,SUM(nox*1) AS nox FROM DB_2017 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT ocountry as key0,SUM(nox*1) AS nox FROM DB_2017 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT dcountry as key0,SUM(nox*1) AS nox FROM DB_2017 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT otrip as key0,SUM(nox*1) AS nox FROM DB_2017 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT dtrip as key0,SUM(nox*1) AS nox FROM DB_2017 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT extract(dow from datet) as key0,SUM(nox*1) AS nox FROM DB_2017 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT extract(hour from datet) as key0,SUM(nox*1) AS nox FROM DB_2017 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT ip as key0,SUM(nox*1) AS nox FROM DB_2017 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;

SELECT cast((cast(meit as float) - 1) * 1 as int) as key0,SUM(nox*1) AS nox FROM DB_2018 WHERE (meit >= 1 AND meit <= 23) AND nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT prov as key0,SUM(nox*1) AS nox FROM DB_2018 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT class as key0,SUM(nox*1) AS nox FROM DB_2018 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT type as key0,SUM(nox*1) AS nox FROM DB_2018 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT mode as key0,SUM(nox*1) AS nox FROM DB_2018 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT engine as key0,SUM(nox*1) AS nox FROM DB_2018 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT ocountry as key0,SUM(nox*1) AS nox FROM DB_2018 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT dcountry as key0,SUM(nox*1) AS nox FROM DB_2018 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT otrip as key0,SUM(nox*1) AS nox FROM DB_2018 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT dtrip as key0,SUM(nox*1) AS nox FROM DB_2018 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT extract(dow from datet) as key0,SUM(nox*1) AS nox FROM DB_2018 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT extract(hour from datet) as key0,SUM(nox*1) AS nox FROM DB_2018 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;
SELECT ip as key0,SUM(nox*1) AS nox FROM DB_2018 WHERE nox*1 IS NOT NULL GROUP BY key0 ORDER BY nox DESC LIMIT 100;


}